axelarnetwork/axelar-cgp-sui

- move/axelar/Move.toml
- scripts/publish-package.js
In order to be able to use `scripts/publish-package.js` in devnet orchestration:
* Allowed for passing of entire environment via command argument (i.e., both alias and url instead of only the alias)
* Made usage of faucet optional
* Fixed a few bugs related to importing/saving package info from/to disk
> chore(scripts): improve `publish-package.js`

- move/test/Move.toml
- move/test/sources/interchain-token-service/coin_info.move
- move/test/sources/interchain-token-service/coin_management.move
- move/test/sources/interchain-token-service/discovery.move
- move/test/sources/interchain-token-service/interchain_address_tracker.move
- move/test/sources/interchain-token-service/interchain_token_channel.move
- move/test/sources/interchain-token-service/service.move
- move/test/sources/interchain-token-service/storage.move
- move/test/sources/interchain-token-service/token_id.move
- move/test/sources/interchain-token-service/utils.move
- removes unnecessary type params
- minor cleanups, ordering
- address is shortened to "its"
- "its::its_utils" -> "its::utils"
- some documentation comments
- simpler TokenChannel (no uid inside)
> [review] 3/X - cleanup, shorter package address, module renames

- .github/workflows/test.yaml
- move/abi/sources/abi.move
- move/axelar/Move.toml
- move/its/sources/discovery.move
- move/its/tests/coin_init_test.move
- scripts/utils.js
I have seen `fs.existsSync` returning `true` even if the file doesn't exist, which then results in a json parsing error. So get around this, this PR generalizes error handling via try/catch when parsing package info.
> fix(scripts): generalize error handling in `utils.setConfig`

- move/gas_service/sources/gas_service.move
[AXE-4139]
[AXE-4139]: https://axelarnetwork.atlassian.net/browse/AXE-4139?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> test(gas_service): additional coverage

- .github/actions/install/action.yaml
Fix missing sui-test-validator in cached binaries
> chore: add sui-validator to sui-binaries

- .gitignore
- src/utils.ts
- test/utils.js
[AXE-4427]
[AXE-4427]: https://axelarnetwork.atlassian.net/browse/AXE-4427?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add copy util to avoid overriding Move.toml for recursive publishes.

- package.json
This PR added `move/test` into `files` array (by removing the excluding line) because we have a script to deploy it in the contract deployment repo
> chore: include `move/test` into published package

- .changeset/itchy-geese-reply.md
- package-lock.json
- package.json
After [we've migrated our code](https://github.com/axelarnetwork/axelar-contract-deployments/pull/315) in `axelar-contracts-deployment` repo to use `axelar-cgp-sui@0.3.0`, we can now safely remove the `postinstall` script and the `src` folder from the published content.
This PR also removed `child_process` and `fs` which are included in `node.js` environment, but ts can't detect the type out-of-the-box, so i've also installed `@types/node` type to fix it.
> chore: cleanup package.json

- .changeset/violet-llamas-visit.md
- .github/workflows/create-release-pr.yaml
- .github/workflows/publish-to-npm.yaml
- CHANGELOG.md
- package.json
This PR fixes the release workflow where it doesn't actually publish the package to npm and create GH release when the changeset pr is merged to main branch. 
The reason is that the release workflow is only triggered on workflow dispatch. That means when we merge the changeset PR to main branch, it will never trigger the release workflow to run again.
So, this PR breaks that release workflow into 2 different workflows as follows:
1. `Create Release Pull Request` :  This workflows will create a PR to update changelog. It's triggered **manually** with workflow dispatch.
2. `Publish to NPM`: This workflow will publish the package to NPM and also create a GH release. It's triggered **automatically** when the `Create Release Pull Request` PR is merged to main branch.
> chore: fix release workflow

- .github/workflows/publish-to-npm.yaml
- package.json
As I've experimented around the `changeset publish` command on a separate repo. I've found that the reason of [this failed job](https://github.com/axelarnetwork/axelar-cgp-sui/actions/runs/10368105174/job/28700966406) is the missing of `NODE_AUTH_TOKEN` in the `Create GitHub Release` step. So, i've reverted [this changes](https://github.com/axelarnetwork/axelar-cgp-sui/pull/100) and provide `NODE_AUTH_TOKEN` in the `env` vars instead.
> chore: fix changeset publish and gh release

- package.json
In our [recent publish-to-npm job](https://github.com/axelarnetwork/axelar-cgp-sui/actions/runs/10573388992), the package was published as a private package. This PR fixes it by explicitly set  `publishConfig.access` to `public` in `package.json`
> chore: fix private package when publish

- move/axelar_gateway/sources/gateway.move
[AXE-4734](https://axelarnetwork.atlassian.net/browse/AXE-4734)
This PR uses enum to simplify MessageStatus struct in the gateway contract
[AXE-4734]: https://axelarnetwork.atlassian.net/browse/AXE-4734?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: utillize enum in gateway contract

- move/example/sources/its/its.move
- test/its.js
- test/testutils.js
This PR fixes test for the new versioned ITS. 
- Most changes are due to `service.move` was now merged to `its.move`, so any move calls should be targetted on `its`, instead of `service`. 
- Another change is to update a way to get channelId from the `ITS_V0` object instead of `ITS` object
> fix: its example for versioned ITS

- .changeset/five-houses-perform.md
- move/example/sources/its/its.move
- move/its/sources/discovery.move
- test/its.js
- test/testdata/interface_example_its.json
[AXE-6061]
[AXE-6061]: https://axelarnetwork.atlassian.net/browse/AXE-6061?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(its)!: fix ITS discovery and verify it in js tests

- .changeset/eight-candles-rest.md
- move/example/sources/its/its.move
- move/its/sources/events.move
- move/its/sources/its.move
- move/its/sources/types/coin_data.move
- move/its/sources/types/coin_info.move
- move/its/sources/types/coin_management.move
- move/its/sources/types/token_id.move
- move/its/sources/versioned/its_v0.move
- move/squid/sources/squid/squid.move
- move/squid/sources/squid/versioned/squid_v0.move
- test/squid.js
- test/testdata/interface_its_coin_info.json
- test/testdata/interface_its_token_id.json
[AXE-6308]
[AXE-6308]: https://axelarnetwork.atlassian.net/browse/AXE-6308?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(its)!: remove remote decimals

- move/its/sources/discovery.move
- move/its/sources/its.move
- move/its/sources/types/address_tracker.move
- move/its/sources/types/coin_management.move
- move/its/sources/types/flow_limit.move
- move/its/sources/types/owner_cap.move
- move/its/sources/types/trusted_addresses.move
- move/its/sources/utils.move
- move/its/sources/versioned/its_v0.move
[AXE-6524]
[AXE-6524]: https://axelarnetwork.atlassian.net/browse/AXE-6524?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(its)!: full its coverage

- .changeset/short-bananas-promise.md
- move/its/sources/events.move
- move/its/sources/its.move
- move/its/sources/types/coin_management.move
- move/its/sources/versioned/its_v0.move
[AXE-6655]
[AXE-6655]: https://axelarnetwork.atlassian.net/browse/AXE-6655?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(its)!: expose set_flow limit for the operator and add a corresponding event

- .changeset/tough-buttons-obey.md
- move/axelar_gateway/sources/gateway.move
- move/axelar_gateway/sources/types/owner_cap.move
- move/axelar_gateway/sources/versioned/gateway_v0.move
- move/version_control/sources/version_control.move
- scripts/limits.js
- test/axelar-gateway.js
- test/its.js
- test/squid.js
- test/testdata/interface_axelar_gateway_gateway.json
- test/testdata/interface_axelar_gateway_owner_cap.json
- test/testdata/interface_version_control_version_control.json
[AXE-6703]
[AXE-6703]: https://axelarnetwork.atlassian.net/browse/AXE-6703?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(version_control,axelar_gateway)!: version control update to axelar_gateway

- .changeset/hungry-days-glow.md
- move/example/sources/its/its.move
- test/testdata/interface_example_its.json
https://axelarnetwork.atlassian.net/browse/AXE-7700
To unblock ITS portal to support mint/burn token deployment
> feat: add register_coin_with_cap function

- move/interchain_token_service/sources/interchain_token_service.move
- move/interchain_token_service/sources/versioned/interchain_token_service_v0.move
This PR adds a migrate entry point function to ITS, and its corresponding package function to its_v0. Additionally it adds unit test coverage.
The code I used was borrowed from [this branch](https://github.com/axelarnetwork/axelar-cgp-sui/tree/feat/upgrade-testing) but I think we should find a different way for enforcing linear upgrades and avoiding migrating to the same upgrade twice, because it blocks unit testing coverage. The `ECannotMigrateTwice` assertion is currently commented out.
> feat(its): migrate function for version control

- src/node/node-utils.ts
- test/utils.js
This PR refactors Move compilation to retire the legacy toml format that uses the `[addresses]` table and `published-at` field to determine on-chain dependencies. 
The PR has been on-chain and confirmed to be working as expected. More specifically, the following requirements have been tested:
- Deploying new contracts works
- Upgrading contracts works
- `sync` command is no longer required post-upgrade (toml / lock are updated automatically)
- `sync` command can be used to update all contracts with legacy toml / lock format to the new format
- `updateMoveToml` remains backwards compatible, making it safe to merge the [implementation PR](https://github.com/axelarnetwork/axelar-contract-deployments/pull/1038) before publishing 1.2.0 to npm (as long as no one runs the `sync` command which …
> chore: refactor move compilation to retire legacy toml format

- .changeset/easy-llamas-eat.md
- src/common/utils.ts
- src/node/node-utils.ts
- test/utils.js
This PR includes the following changes:
* deprecated faucet function`requestSuiFromFaucetV0` is updated to `requestSuiFromFaucetV2` (with fallback to v0 for `localnet`)
* deprecated type alias `TomlPrimitive` is updated to `TomlValue`
* function `updateMoveToml` now updates move toml and lock files correctly for upgraded contracts, based on three new param inputs: version, sui network and legacy package id
> fix: update move toml and lock files correctly based on version and network
