axelarnetwork/axelar-cgp-sui

move/test/sources/interchain-token-service/coin_info.move, move/test/sources/interchain-token-service/coin_managment.move, move/test/sources/interchain-token-service/discovery.move, move/test/sources/interchain-token-service/service.move
Notes:
- some doc additions
- no more has_ability
- better vector management
- minor improvements
=> [review] 1/X - cleanup: discovery, info, coin management

move/axelar_gateway/sources/channel.move, move/axelar_gateway/sources/gateway.move
[AXE-3822]
[AXE-3822]: https://axelarnetwork.atlassian.net/browse/AXE-3822?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(channel)!: remove approval tracking from channels

move/axelar_gateway/sources/types/weighted_signer.move
[AXE-3822]
[AXE-3822]: https://axelarnetwork.atlassian.net/browse/AXE-3822?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(auth): initialize signer to 0 bytes

.github/workflows/codecov.yaml, .github/workflows/test.yaml, package.json, scripts/coverage.sh
[AXE-4067]
[AXE-4067]: https://axelarnetwork.atlassian.net/browse/AXE-4067?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ci: cache sui binaries in gh actions

.github/workflows/codecov.yaml, scripts/coverage.sh
[AXE-4066]
[AXE-4066]: https://axelarnetwork.atlassian.net/browse/AXE-4066?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ci: show code coverage summary as a comment

.github/workflows/codecov.yaml, .github/workflows/test.yaml, scripts/coverage.sh
[AXE-4066]
[AXE-4066]: https://axelarnetwork.atlassian.net/browse/AXE-4066?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ci: show extended summary separately

move/abi/Move.toml, move/abi/sources/abi.move, move/axelar_gateway/Move.toml, move/axelar_gateway/sources/types/bytes32.move, move/gas_service/Move.toml, move/governance/Move.toml, move/governance/sources/governance/governance.move, move/interchain_token/Move.toml, move/its/Move.toml, move/its/sources/discovery.move, move/its/sources/service.move, move/squid/Move.toml, move/test/Move.toml
[AXE-4063]
[AXE-4063]: https://axelarnetwork.atlassian.net/browse/AXE-4063?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor(abi): add position tracking to abi reader

.github/workflows/lint.yaml, scripts/test-receive-call.js
[AXE-4141]
[AXE-4141]: https://axelarnetwork.atlassian.net/browse/AXE-4141?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ci: add lint action

package.json, scripts/coverage.sh, scripts/gateway.js, scripts/governance.js, scripts/publish-all.js, scripts/publish-package.js, scripts/run.sh, scripts/test-receive-call.js, scripts/test-send-call.js, scripts/test-transfer-operatorship.js, scripts/utils.js
[AXE-4144]
[AXE-4144]: https://axelarnetwork.atlassian.net/browse/AXE-4144?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ci: fail actions on build/test failure

.github/workflows/codecov.yaml, .github/workflows/test.yaml, move/abi/Move.toml, move/axelar_gateway/Move.toml, move/gas_service/Move.toml, move/governance/Move.toml, move/interchain_token/Move.toml, move/its/Move.toml, move/squid/Move.toml, move/test/Move.toml, scripts/coverage.sh
[AXE-4149]
[AXE-4149]: https://axelarnetwork.atlassian.net/browse/AXE-4149?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: fix sui framework dep tag

README.md, move/abi/Move.lock, move/abi/Move.toml, move/axelar_gateway/Move.lock, move/axelar_gateway/Move.toml, move/gas_service/Move.lock, move/gas_service/Move.toml, move/governance/Move.lock, move/governance/Move.toml, move/interchain_token/Move.lock, move/interchain_token/Move.toml, move/its/Move.lock, move/its/Move.toml, move/squid/Move.lock, move/squid/Move.toml, move/test/Move.lock, move/test/Move.toml, scripts/run.sh
[AXE-4149]
[AXE-4149]: https://axelarnetwork.atlassian.net/browse/AXE-4149?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ci: pin sui dep version

move/abi/sources/abi.move, move/its/sources/service.move
[AXE-4151]
[AXE-4151]: https://axelarnetwork.atlassian.net/browse/AXE-4151?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor(abi): clean up abi writer

move/its/sources/discovery.move, move/its/sources/its.move, move/its/sources/service.move, move/its/sources/token_id.move, move/test/sources/test/test.move
[AXE-4126]
[AXE-4126]: https://axelarnetwork.atlassian.net/browse/AXE-4126?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor(SUI): move syntax update

move/axelar_gateway/sources/auth.move
[AXE-4212]
[AXE-4212]: https://axelarnetwork.atlassian.net/browse/AXE-4212?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(axelar-gateway): prevent signer threshold from being zero

.changeset/twelve-jokes-confess.md, move/axelar_gateway/sources/auth.move, move/axelar_gateway/sources/gateway.move, test/axelar-gateway.js
[AXE-4477]
[AXE-4477]: https://axelarnetwork.atlassian.net/browse/AXE-4477?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(gateway)!: add previous signer retention to gateway setup

.changeset/hip-ears-act.md, src/index.ts, src/types.ts
=> feat: add uid type

move/test/Move.lock, move/test/Move.toml, move/test/sources/test/test.move
[AXE-4529](https://axelarnetwork.atlassian.net/browse/AXE-4529)
Includes paying gas into send_call to mimic evm's call contract example
[AXE-4529]: https://axelarnetwork.atlassian.net/browse/AXE-4529?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add pay_gas into send_call in test module

.changeset/funny-coins-act.md
Add changeset file for [this PR](https://github.com/axelarnetwork/axelar-cgp-sui/pull/90)
=> chore: update changeset file

.gitignore
To unblock release action https://github.com/axelarnetwork/axelar-cgp-sui/actions/runs/10280727655/job/28448682638
=> chore: ignore sui-binaries

.github/workflows/create-release-pr.yaml, docs/release.md
- Fix the workflow error here https://github.com/axelarnetwork/axelar-cgp-sui/actions/runs/10301872004/job/28514347507
- Update the release doc
=> chore: fix create release pr workflow and update release doc

.changeset/pray-three-times.md, package.json
Fix failed publish-to-npm workflow [here](https://github.com/axelarnetwork/axelar-cgp-sui/actions/runs/10319507892/job/28568922998)
=> chore: update release script

.github/workflows/publish-to-npm.yaml
an attempt to fix failed publish workflow https://github.com/axelarnetwork/axelar-cgp-sui/actions/runs/10368105174/job/28700966406
=> chore: separate publish to npm workflow

.changeset/nice-dodos-destroy.md, src/bcs.ts
Added `Bag` and `Operators` structs.
=> chore: add operators struct

.changeset/perfect-tips-dress.md, move/example/Move.lock, move/example/Move.toml, move/example/info.json, move/example/sources/gmp/gmp.move, package-lock.json
[AXE-4681](https://axelarnetwork.atlassian.net/browse/AXE-4681)
[AXE-4681]: https://axelarnetwork.atlassian.net/browse/AXE-4681?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: rename test package

.changeset/few-penguins-sort.md, src/bcs.ts, src/tx-builder.ts
This PR adds missing structs for sui scripts in the `axelar-contracts-deployment` repos, so we could importing structs from here instead of creating new structs there.
=> chore: add more structs

.changeset/new-suits-mate.md, .changeset/stupid-rings-worry.md, move/operators/sources/operators.move
[AXE-4707]
[AXE-4707]: https://axelarnetwork.atlassian.net/browse/AXE-4707?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: simplify the operators module.

.changeset/hot-penguins-sneeze.md, move/abi/Move.lock, move/abi/Move.toml, move/axelar_gateway/Move.lock, move/axelar_gateway/Move.toml, move/example/Move.lock, move/example/Move.toml, move/gas_service/Move.lock, move/gas_service/Move.toml, move/governance/Move.lock, move/governance/Move.toml, move/interchain_token/Move.lock, move/interchain_token/Move.toml, move/its/Move.lock, move/its/Move.toml, move/its/sources/service.move, move/operators/Move.lock, move/operators/Move.toml, move/squid/Move.lock, move/squid/Move.toml
Updated sui rev from `mainnet-v1.25.3` to `testnet-v1.32.0`
=> chore: update lock file

.changeset/forty-ghosts-tie.md, .changeset/popular-trains-agree.md, .github/actions/install/action.yaml, move/abi/Move.lock, move/abi/Move.toml, move/axelar_gateway/Move.lock, move/axelar_gateway/Move.toml, move/example/Move.lock, move/example/Move.toml, move/gas_service/Move.lock, move/gas_service/Move.toml, move/governance/Move.lock, move/governance/Move.toml, move/interchain_token/Move.lock, move/interchain_token/Move.toml, move/its/Move.lock, move/its/Move.toml, move/operators/Move.lock, move/operators/Move.toml, move/squid/Move.lock, move/squid/Move.toml, version.json
Enhances Sui workflow reusability by changing Sui download path to avoid conflicts with `axelar-contract-deployment` repo, allowing custom `version.json` path, and refactoring for easier integration across projects.
=> chore: make sui workflow reusable

.changeset/old-zebras-own.md, package.json
Include `version.json` file in the published package to be used in `axelar-contract-deployments` workflow
=> chore: include version.json file

.changeset/gold-worms-whisper.md, move/axelar_gateway/sources/discovery.move
Refactor `axelar_gateway::discovery` module to replace loops with `vector::tabulate`
=> chore: refactor discovery module

.changeset/blue-queens-bow.md, src/utils.ts, test/utils.js
https://axelarnetwork.atlassian.net/browse/AXE-5031
=> feat: add get package dependencies

move/axelar_gateway/sources/auth.move, move/axelar_gateway/sources/channel.move, move/axelar_gateway/sources/events.move, move/axelar_gateway/sources/gateway.move, move/axelar_gateway/sources/types/gateway_data.move, move/axelar_gateway/sources/types/message_status.move, move/axelar_gateway/sources/types/message_ticket.move, move/axelar_gateway/sources/versioned/gateway_v0.move, move/example/sources/gmp/gmp.move, move/gas_service/sources/gas_service.move, move/its/sources/its.move, move/its/sources/service.move, move/squid/sources/squid/squid.move, move/version_control/sources/version_control.move, test/axelar-gateway.js
[AXE-4869]
[AXE-4869]: https://axelarnetwork.atlassian.net/browse/AXE-4869?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(axelar-gateway)!: version gateway package

.changeset/short-bottles-hope.md, move/axelar_gateway/sources/auth.move, move/axelar_gateway/sources/channel.move, move/axelar_gateway/sources/types/message_ticket.move, move/axelar_gateway/sources/types/proof.move, move/axelar_gateway/sources/versioned/gateway_v0.move, package-lock.json, test/axelar-gateway.js, test/testutils.js
Mimic redundant signature [check](https://github.com/axelarnetwork/axelar-gmp-sdk-solidity/blob/main/contracts/governance/BaseWeightedMultisig.sol#L223) as in EVM
[AXE-5781]
[AXE-5781]: https://axelarnetwork.atlassian.net/browse/AXE-5781?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(axelar_gateway): add redundant signature check

.changeset/violet-bugs-count.md, move/its/sources/discovery.move, move/its/sources/events.move, move/its/sources/its.move, move/its/sources/versioned/its_v0.move, test/testdata/interface_its_events.json, test/testdata/interface_its_its.json
[AXE-5856]
[AXE-5856]: https://axelarnetwork.atlassian.net/browse/AXE-5856?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(its)!: added events file and move all logic to versioned

move/example/sources/its/its.move, test/its.js, test/testdata/interface_example_its.json
This PR allows any token to be passed into the its example functions
=> chore: allow any token to be used in its example contract

move/its/sources/discovery.move
[AXE-6038]
[AXE-6038]: https://axelarnetwork.atlassian.net/browse/AXE-6038?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(its)!: fix its discovery

move/its/sources/versioned/its_v0.move
[AXE-6054]
[AXE-6054]: https://axelarnetwork.atlassian.net/browse/AXE-6054?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(ITS)!: update ITS hub chain name

.changeset/olive-masks-exercise.md, package-lock.json, package.json, src/execute.ts, src/index.ts, src/types.ts, src/utils.ts, test/axelar-gateway.js, test/its.js
https://axelarnetwork.atlassian.net/browse/AXE-6070
This PR refactors and converts `approve` and `execute` functions in the `testutils` file into typescript and export it so that other projects could utilize them.
=> feat: export approve and execute function

move/its/sources/types/coin_management.move, move/its/sources/types/flow_limit.move, move/its/sources/types/token_id.move, test/testdata/interface_its_flow_limit.json, test/testdata/interface_its_token_id.json
Also added `remote_decimals` to `its::token_id` derivation.
=> feat: addressed ottersec audit comments

.changeset/dull-humans-fold.md, move/axelar_gateway/sources/auth.move, move/axelar_gateway/sources/channel.move, move/axelar_gateway/sources/gateway.move, move/axelar_gateway/sources/types/bytes32.move, move/axelar_gateway/sources/types/message_ticket.move, move/axelar_gateway/sources/types/proof.move, move/axelar_gateway/sources/types/weighted_signer.move, move/axelar_gateway/sources/types/weighted_signers.move, move/axelar_gateway/sources/versioned/gateway_v0.move
[AXE-6309]
[AXE-6309]: https://axelarnetwork.atlassian.net/browse/AXE-6309?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> test(axelar_gateway): use random inputs in gateway tests

.changeset/late-goats-smell.md, move/relayer_discovery/sources/discovery.move, move/relayer_discovery/sources/events.move, move/relayer_discovery/sources/versioned/relayer_discovery_v0.move, test/testdata/interface_relayer_discovery_events.json
[AXE-4563]
[AXE-4563]: https://axelarnetwork.atlassian.net/browse/AXE-4563?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
https://axelarnetwork.atlassian.net/browse/AXE-4178
=> feat(relayer_discovery)!: added events to relayer discovery

.changeset/wild-eagles-unite.md, move/gas_service/sources/events.move, move/gas_service/sources/gas_service.move, move/gas_service/sources/versioned/gas_service_v0.move, move/relayer_discovery/Move.toml, test/testdata/interface_gas_service_events.json
[AXE-6529]
[AXE-6529]: https://axelarnetwork.atlassian.net/browse/AXE-6529?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(gas_service)!: move gas service logic to versioned

.changeset/eighty-eggs-cross.md, move/its/sources/events.move, move/its/sources/types/address_tracker.move, test/testdata/interface_its_events.json
[AXE-6656]
[AXE-6656]: https://axelarnetwork.atlassian.net/browse/AXE-6656?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(its)!: added its events for setting and removing trusted addresses.

move/interchain_token_service/sources/events.move, move/interchain_token_service/sources/interchain_token_service.move, move/interchain_token_service/sources/types/coin_management.move, move/interchain_token_service/sources/types/flow_limit.move, move/interchain_token_service/sources/versioned/interchain_token_service_v0.move, test/testdata/interface_interchain_token_service_flow_limit.json
[AXE-7211]
[AXE-7211]: https://axelarnetwork.atlassian.net/browse/AXE-7211?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(its)!: change flow limit to an option<u64>

move/interchain_token_service/sources/events.move, move/interchain_token_service/sources/interchain_token_service.move, move/interchain_token_service/sources/types/coin_data.move, move/interchain_token_service/sources/types/coin_management.move, move/interchain_token_service/sources/types/token_id.move, move/interchain_token_service/sources/versioned/interchain_token_service_v0.move, test/testdata/interface_interchain_token_service_coin_data.json, test/testdata/interface_interchain_token_service_coin_management.json, test/testdata/interface_interchain_token_service_interchain_token_service.json
[AXE-7384]
[AXE-7384]: https://axelarnetwork.atlassian.net/browse/AXE-7384?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(its)!: adding some getters and the ability to transfer operator/distributor
